app_name: port-scanner
app_user: scanner
app_group: scanner
app_dir: /opt/port-scanner

masscan_rate: "1000"
masscan_ports: "22,53,80,443,1883,8080,9883"
masscan_interface: ""

scan_targets:
  - "192.168.64.5"

scheduler_enabled: true
scheduler_interval: "30m"

telegram_enabled: true
smtp_enabled: false

smtp_host: "smtp.gmail.com"
smtp_port: 587

telegram_token: "{{ vault_telegram_token }}"
telegram_chat_id: "{{ vault_telegram_chat_id }}"
smtp_user: "{{ vault_smtp_user }}"
smtp_password: "{{ vault_smtp_password }}"
smtp_from: "{{ vault_smtp_from }}"
smtp_to: "{{ vault_smtp_to }}"
